version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=focvs
    ports:
      - 5432:5432
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123
    ports:
      - 27017:27017
  redis:
    image: redis
    command: ['redis-server', '--port', '6379']
    ports:
      - 6379:6379
    volumes:
      - cache:/cache
volumes:
  cache:
